[2024-05-21T14:29:33.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T14:29:33.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.get_name scheduled__2021-10-10T00:00:00+00:00 [queued]>
[2024-05-21T14:29:33.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.get_name scheduled__2021-10-10T00:00:00+00:00 [queued]>
[2024-05-21T14:29:33.518+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-21T14:29:33.639+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_name> on 2021-10-10 00:00:00+00:00
[2024-05-21T14:29:33.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v07', 'get_name', 'scheduled__2021-10-10T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmp_vcco_xr']
[2024-05-21T14:29:33.837+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2548) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T14:29:33.858+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask get_name
[2024-05-21T14:29:33.860+0000] {standard_task_runner.py:63} INFO - Started process 2566 to run task
[2024-05-21T14:29:34.034+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v07.get_name scheduled__2021-10-10T00:00:00+00:00 [running]> on host c420abfdc210
[2024-05-21T14:29:34.269+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v07' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2021-10-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-10T00:00:00+00:00'
[2024-05-21T14:29:34.271+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T14:29:34.480+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T14:29:34.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T14:29:34.509+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v07, task_id=get_name, run_id=scheduled__2021-10-10T00:00:00+00:00, execution_date=20211010T000000, start_date=20240521T142933, end_date=20240521T142934
[2024-05-21T14:29:34.588+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T14:29:34.643+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T14:29:34.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
