[2024-05-27T14:21:12.227+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T14:21:12.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table manual__2024-05-27T14:21:10.694012+00:00 [queued]>
[2024-05-27T14:21:12.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table manual__2024-05-27T14:21:10.694012+00:00 [queued]>
[2024-05-27T14:21:12.251+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-27T14:21:12.264+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-05-27 14:21:10.694012+00:00
[2024-05-27T14:21:12.269+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=560) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T14:21:12.271+0000] {standard_task_runner.py:63} INFO - Started process 561 to run task
[2024-05-27T14:21:12.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'manual__2024-05-27T14:21:10.694012+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp8bdu3b_7']
[2024-05-27T14:21:12.272+0000] {standard_task_runner.py:91} INFO - Job 141: Subtask insert_into_table
[2024-05-27T14:21:12.307+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table manual__2024-05-27T14:21:10.694012+00:00 [running]> on host d44ae21ae39e
[2024-05-27T14:21:12.373+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T14:21:10.694012+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-27T14:21:10.694012+00:00'
[2024-05-27T14:21:12.374+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T14:21:12.383+0000] {sql.py:276} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-05-27', 'test')
        
[2024-05-27T14:21:12.390+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-27T14:21:12.397+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-27T14:21:12.407+0000] {sql.py:470} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-05-27', 'test')
        , parameters: None
[2024-05-27T14:21:12.411+0000] {sql.py:479} INFO - Rows affected: 1
[2024-05-27T14:21:12.416+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T14:21:12.423+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, run_id=manual__2024-05-27T14:21:10.694012+00:00, execution_date=20240527T142110, start_date=20240527T142112, end_date=20240527T142112
[2024-05-27T14:21:12.445+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T14:21:12.457+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T14:21:12.461+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
