[2024-05-21T14:31:06.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T14:31:06.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.get_name scheduled__2022-02-14T00:00:00+00:00 [queued]>
[2024-05-21T14:31:06.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.get_name scheduled__2022-02-14T00:00:00+00:00 [queued]>
[2024-05-21T14:31:06.671+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-21T14:31:06.699+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_name> on 2022-02-14 00:00:00+00:00
[2024-05-21T14:31:06.708+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3334) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T14:31:06.711+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v07', 'get_name', 'scheduled__2022-02-14T00:00:00+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmpfeihm4iu']
[2024-05-21T14:31:06.713+0000] {standard_task_runner.py:63} INFO - Started process 3344 to run task
[2024-05-21T14:31:06.714+0000] {standard_task_runner.py:91} INFO - Job 403: Subtask get_name
[2024-05-21T14:31:06.790+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v07.get_name scheduled__2022-02-14T00:00:00+00:00 [running]> on host c420abfdc210
[2024-05-21T14:31:06.921+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v07' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2022-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-02-14T00:00:00+00:00'
[2024-05-21T14:31:06.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T14:31:06.968+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T14:31:06.970+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T14:31:06.983+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v07, task_id=get_name, run_id=scheduled__2022-02-14T00:00:00+00:00, execution_date=20220214T000000, start_date=20240521T143106, end_date=20240521T143106
[2024-05-21T14:31:07.012+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T14:31:07.042+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-21T14:31:07.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
